image: node:10.15.3

pipelines:
  branches:
    '{master}':
      - step:
        caches:
          - node
        name: build and deploy master
        script:
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
